### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [WAYNGROUP/MGM-Skill#7]
Git tag: 0.2.0-preview
package.json's version: 0.1.2-preview

To fix: bump version, then re-tag 0.2.0-preview.

To avoid it in the future, recommended readings:
- Managing release with CLI https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163
- Managing release with CI: https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c

----
The issue is detected by [openupm](https://openupm.com/packages/wayn-group.mgm.skill/) build pipelines (right bottom "build issues" section). OpenUPM is an open-source UPM registry with automatic build pipelines.

**Comment by WaynGames** [comment]
Fixed.
Thanks for the issue and sugested reading.
I'll do my best to keep it consistent over the next releases.
